services:
  db:
    image: postgres:14
    container_name: postgres_container
    environment:
      POSTGRES_DB: sadb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 643admin643x!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
