server:
  port: ${PORT:8080}
spring:
    datasource:
      url: ${JDBC_DATABASE_URL}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
    liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yaml
    telegram:
      bot-name: sealert_bot
      token: 6892574449:AAFSqSWG5U0c0mPNyRMfgkInoooRQ7XM2Qo
      url: https://api.telegram.org/bot6892574449:AAFSqSWG5U0c0mPNyRMfgkInoooRQ7XM2Qo/sendMessage
    text:
      welcome: "Добро пожаловать! Я бот, который уведомляет о плановых отключениях электричества в Сербии.\nЧтобы получать актуальные оповещения, пожалуйста, подпишитесь на рассылку и выберите интересующий вас регион c помощью команды /get_districts.\nДля дополнительной информации о работе бота используйте команду /info."
      notification: "Для получения актуальных уведомлений на текущий момент вызовите команду /get"
      get-district: "Введите команду /add_district, затем укажите один или несколько регионов через запятую, чтобы получать по ним уведомления."
      district-subscription: "Подписка успешно оформлена.\nДля получения актуальных уведомлений прямо сейчас используйте команду /get.\nБудущие уведомления будут отправляться автоматически.\nДля отмены подписки на выбранный регион используйте команду /delete_district."
      info: "@sealert_bot — это бот для автоматической рассылки уведомлений о плановых и аварийных отключениях электричества в Сербии. Информация собирается с официального сайта https://www.elektrodistribucija.rs/ и оперативно направляется подписчикам.\nКоманды бота:\n/start — запустить бота и начать процесс подписки на уведомления. Вам будет предложено выбрать регион, чтобы получать уведомления о плановых и аварийных отключениях в вашем регионе.\n/get — получить актуальную информацию об отключениях электроэнергии на текущий момент в вашем регионе.\n/add_district — добавить новый регион для получения уведомлений. Вы можете подписаться на несколько регионов, если вам нужно отслеживать отключения в нескольких местах.\n/delete_district — удалить регион из списка подписок. Это удобно, если вы больше не хотите получать уведомления по определённому региону.\n/get_districts — посмотреть список всех доступных для подписки регионов.\n/cancel — отменить подписку и прекратить получение уведомлений. Вы всегда сможете возобновить подписку с помощью команды /start."
      delete-district: "Подписка на указанный регион успешна удалена."
      bye: "Ваша подписка была успешно отменена. Спасибо, что использовали наш бот!\nЕсли решите вернуться, команда /start всегда доступна для вас."
    rest-client:
        auth-header: e27ffb11-bdf2-4c0c-b0b9-2c17cab026e4
